version: "3.9"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: bank_holiday
    ports:
      - "13306:3306"
  bankholiday:
    depends_on:
      - mysql
      - redis
    build:
      context: .
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path":"/bank-holiday-api",
        "spring.datasource.url":"jdbc:mysql://mysql:3306/bank_holiday?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
        "spring.datasource.username": "root",
        "spring.datasource.password": "test1234",
        "spring.cache.type": "redis",
        "spring.redis.host":"redis"
      }'
    ports:
      - "8080:8080"

