version: "3.9"
services:
  bankholiday_redis:
    image: redis:6.2-alpine
  bankholiday_mysql:
    image: mysql:8.0
  bankholiday_rabbitmq:
    image: rabbitmq:3-management
  bankholiday_application:
    depends_on:
      - bankholiday_mysql
      - bankholiday_redis
      - bankholiday_rabbitmq
    image: ghcr.io/couryrr/bank-holiday-api:main


